name: Build
on: workflow_dispatch

jobs:
  build_apk_aab:
    name: Build release artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '19'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew assemble --no-daemon
          {
            echo "version=v$(grep versionName app/build.gradle.kts | awk '{print $3}' | tr -d \")"
            echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
          } >> "$GITHUB_ENV"
          ls app/build/outputs/apk/*
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Bluetooth-LE-Spam(${{ env.version }}@${{ env.commit }})
          path: app/build/outputs/apk/**/app-*.apk
      - name: Ls
        run: ls /app/build/outputs/apk_from_bundle/release/*
